import type { Metadata } from "next";
import '@/styles/globals.css';
import StoreProvider from "../store/StoreProvider";

import { AppShell } from "@/components/layout/AppShell";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <StoreProvider>


            <AppShell>
              {children}
            </AppShell>

        </StoreProvider>
      </body>
    </html>
  );
}