import type { Metadata } from "next";
import '@/styles/globals.css';
import StoreProvider from "../store/StoreProvider";
import LeftSide from "@/components/layout/LeftSide";
import RightSide from "@/components/layout/RightSide";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <StoreProvider>
          <LeftSide />
          <main className="flex-1">
            {children}
          </main>
          <RightSide />
        
        </StoreProvider>
      </body>
    </html>
  );
}
