import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import StoreProvider from "./(store)/StoreProvider";
import AuthNav from "./(common)/components/auth/AuthNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
        <nav>
          <Link href="/">홈</Link>
          <Link href="/guest-board/list?page=1">비회원게시판</Link>
          <AuthNav />
        </nav>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
